import json
from typing import Dict, Any, List

class TopologyConverter:
    @staticmethod
    def export_gns3(nodes: Dict[str, Any], links: Dict[str, Any]) -> Dict[str, Any]:
        """
        Exports current network twin state to GNS3 schema v2 format
        """
        gns3_nodes = []
        for nid, node in nodes.items():
            gns3_nodes.append({
                "node_id": nid,
                "name": node["name"],
                "node_type": "dynamips" if node["type"] == "router" else "ethernet_switch" if node["type"] == "switch" else "qemu",
                "x": node["x"],
                "y": node["y"],
                "status": "started" if node["status"] == "active" else "stopped",
                "properties": {
                    "platform": "c7200" if node["type"] == "router" else "c3725",
                    "ram": 512,
                    "nvram": 256,
                    "idlepc": "0x60b08058"
                }
            })

        gns3_links = []
        for lid, link in links.items():
            gns3_links.append({
                "link_id": lid,
                "nodes": [
                    {"node_id": link["source"], "adapter_number": 0, "port_number": 0},
                    {"node_id": link["target"], "adapter_number": 0, "port_number": 1}
                ],
                "suspend": link["status"] == "down"
            })

        return {
            "gns3_version": "2.2.38",
            "project_id": "net-digital-twin-project",
            "name": "Network_Digital_Twin_Export",
            "topology": {
                "nodes": gns3_nodes,
                "links": gns3_links
            }
        }

    @staticmethod
    def export_packet_tracer(nodes: Dict[str, Any], links: Dict[str, Any]) -> Dict[str, Any]:
        """
        Exports current network twin state to Cisco Packet Tracer schema structure
        """
        pt_devices = []
        for nid, node in nodes.items():
            pt_devices.append({
                "id": nid,
                "model": "2911 Router" if node["type"] == "router" else "2960 Switch" if node["type"] == "switch" else "Generic PC",
                "label": node["name"],
                "ip_address": node["ip"],
                "subnet_mask": "255.255.255.0",
                "position": {"x": node["x"], "y": node["y"]}
            })

        pt_connections = []
        for lid, link in links.items():
            pt_connections.append({
                "id": lid,
                "from_device": link["source"],
                "to_device": link["target"],
                "cable_type": "Copper Straight-Through" if link["bandwidth"] <= 1000 else "Fiber"
            })

        return {
            "pkt_version": "8.2.1",
            "network_name": "Digital_Twin_Cisco_Export",
            "devices": pt_devices,
            "connections": pt_connections
        }

    @staticmethod
    def generate_cisco_ios_config(node: Dict[str, Any], neighbors: List[Dict[str, Any]]) -> str:
        """
        Generates Cisco IOS CLI configuration for a given router/switch node
        """
        hostname = node["name"].replace(" ", "-")
        ip = node["ip"]
        node_type = node["type"]

        config_lines = [
            f"! Cisco IOS Config Generated by Network Digital Twin Engine",
            f"! Node: {node['name']} ({node['id']})",
            f"!",
            f"version 15.4",
            f"service timestamps debug datetime msec",
            f"service timestamps log datetime msec",
            f"no service password-encryption",
            f"!",
            f"hostname {hostname}",
            f"!",
            f"boot-start-marker",
            f"boot-end-marker",
            f"!",
            f"vrf definition MANAGEMENT",
            f" description Out-of-Band Management VRF",
            f"!",
            f"ip cef",
            f"no ip domain lookup",
            f"ip domain name enterprise.internal",
            f"!",
            f"interface GigabitEthernet0/0",
            f" description Primary Interface",
            f" ip address {ip} 255.255.255.0",
            f" duplex auto",
            f" speed auto",
            f" no shutdown",
            f"!"
        ]

        if node_type == "router":
            config_lines.extend([
                f"router ospf 1",
                f" router-id {ip}",
                f" log-adjacency-changes",
                f" network {ip} 0.0.0.255 area 0",
                f"!"
            ])
            for n in neighbors:
                n_ip = n.get("ip", "10.0.0.1")
                config_lines.append(f" network {n_ip} 0.0.0.255 area 0")

        elif node_type == "switch":
            config_lines.extend([
                f"vlan 10",
                f" name DATA_VLAN",
                f"vlan 20",
                f" name VOICE_VLAN",
                f"!",
                f"interface FastEthernet0/1",
                f" switchport mode access",
                f" switchport access vlan 10",
                f" spanning-tree portfast",
                f"!"
            ])

        config_lines.extend([
            f"line con 0",
            f" logging synchronous",
            f" stopbits 1",
            f"line vty 0 4",
            f" privilege level 15",
            f" login local",
            f" transport input ssh",
            f"!",
            f"end"
        ])

        return "\n".join(config_lines)
